### ISSUE TITLE
Bug when `toFill` matcher try to clear input of type number

### ISSUE THREAD

**Issue by rjurado01** [smooth-code/jest-puppeteer#411]
## 🐛 Bug Report

`toFill` matcher fails when input type is number

## To Reproduce

```html
<input id="input" type="number">
```

```js
await expect(page).toFill('#input', '2018')
await expect(page).toFill('#input', '2018')
```

![image](https://user-images.githubusercontent.com/1703608/119527001-32c27380-bd80-11eb-9ff7-165ad0d81e85.png)

## Expected behavior

Clear value before fill new value

## Technical details

The error occurs on [selectAll](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/src/matchers/toFill.js#L3) method. When line 8 is executed it through this error:

![image](https://user-images.githubusercontent.com/1703608/119527254-71582e00-bd80-11eb-8df0-c11938e9d59e.png)

Then the code: `elementHandle.focus()` is executed but it seems that content is not selected.

I confirm that this code on my chrome / firefox console, does not work either: 

![image](https://user-images.githubusercontent.com/1703608/119528649-aa44d280-bd81-11eb-951a-885f142478ad.png)

I'm runing test on chrome headless using jest-puppeteer 5.0.3

## Possible alternatives

```js
await page.click(selector, {clickCount: 3})
await page.keyboard.press('Backspace')
```

**Comment by UziTech** [comment]
This should be fixed in v5.0.4 :tada:

**Comment by AdamPD** [comment]
I'm still encountering this issue using 10.0.1.  Regression perhaps?
